### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Geordie88**
updating ChatGPT badge image. quick google says uploading a file with the same name should replace the old one but if there are any issues let me know

### CODE REVIEW

**Review by jernejk — APPROVED** [review]
LGTM

**Comment by christianmorfordwaitessw** [comment]
Hi @Geordie88,

1. Can you please resize the badge to `135px width and height`
As per the wiki on adding badges
https://github.com/SSWConsulting/SSW.People.Profiles/wiki/6.-Extras-%E2%80%90-Editing-profiles#extra---adding-your-own-badges

**Review by christianmorfordwaitessw — CHANGES_REQUESTED** [review]
Hi @Geordie88,

Can you please resize the badge to 135px width and height
As per the wiki on adding badges
https://github.com/SSWConsulting/SSW.People.Profiles/wiki/6.-Extras-%E2%80%90-Editing-profiles#extra---adding-your-own-badges

**Review by christianmorfordwaitessw — APPROVED** [review]

**Comment by Geordie88** [comment]
hi @christianmorfordwaitessw, 

thanks for the catch

**Pull request merged**
