### PR TITLE
Update Ben-Cull.md

### PR DESCRIPTION
**Pull request by 2fernandez**
Adding popular Video from Ben as per Adams's request

### CODE REVIEW

**Review by tiagov8 — COMMENTED** [review]
Hey @2fernandez 

The video widget is done by adding a playlist ID to CRM: https://github.com/SSWConsulting/SSW.People.Profiles/wiki/6.-Extras-%E2%80%90-Editing-profiles#extra---youtube-widget

1. Any reason why Ben's wasn't done this way?

**Comment by 2fernandez** [comment]
Hi @tiagov8, 
@adamcogan  specifically asked for this video to be embedded on Ben's profile page as he likes this video, 
not a playlist that might contain other videos.

According to the code on https://www.ssw.com.au/people/jean-thirion page.
I opted for an embed of this video.

**Comment by christianmorfordwaitessw** [comment]
Hi @2fernandez,

1. Can you please change it to the markdown embed syntax, there's an example of it on
https://ssw.com.au/people/sample

It should be something like this
```
`youtube: https://www.youtube.com/embed/bIGiUSMBwoo` 
```

**Comment by 2fernandez** [comment]
```
Can you please change it to the markdown embed syntax, there's an example of it on
https://ssw.com.au/people/sample
```

Done! @christianmorfordwaitessw

**Review by christianmorfordwaitessw — APPROVED** [review]

**Pull request merged**
